stages:
- build

linux:
    stage: build
    script:
        - apt-get update
        - apt-get install --no-install-recommends xz-utils curl git ca-certificates curl -y
        - curl -s https://packagecloud.io/install/repositories/anarchytools/AT/script.deb.sh | bash
        - apt-get install atbuild package-deb -y
        - atbuild check
    tags:
        - autoscale-linux
    image: drewcrawford/swift:latest

osx:
    stage: build
    script: 
        - atbuild check
    tags:
        - openswift
        - atbuild
